name: Bazzite
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@main
    - name: Login to GitHub Container Registry
      run: podman login ghcr.io -u emblem-66 -p ${{ secrets.GITHUB_TOKEN }}
    - name: Build Bazzite Image
      run: podman build -f Containerfile -t ghcr.io/emblem-66/bazzite:stable
    - name: Push Bazzite Image
      run: podman push ghcr.io/emblem-66/bazzite:stable
